name: CommandMob
version: '1.2'
main: com.Lino.CommandMob.SimpleCommandMob
api-version: '1.21'
authors: [Lino9999]
description: Execute commands when players kill specific mobs

commands:
  mobcommands:
    description: Main plugin command
    usage: |
      /<command> reload - Reload the plugin configuration
    aliases: [mobcmd, scm]